spring:
  profiles:
    active: ${PROFILES_ACTIVE:dev}
  resources:
    static-locations:
      - classpath:/META-INF/resources/
  devtools:
    restart:
      enabled: false

#app
server:
    port: 9902
    servlet:
      context-path: /open/api/

